### ISSUE TITLE
Make whonix templates happy to use cacher

### ISSUE THREAD

**Issue by tlaurion** [unman/shaker#12]
1- The following userinfo.html would need to be put under `/usr/lib/apt-cacher-ng/userinfo.html`under cloned template-cacher so that whonix templates proxy check detects a tor enabled local proxy (otherwise fails):
```
<!DOCTYPE html>
<html lang="en"><html>

<head>
<title>403 Filtered</title>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<meta name="application-name" content="tor proxy"/>
</head>

</html>
```

(As stated under https://github.com/unman/shaker/issues/10#issuecomment-1221116802 point 1)

**Comment by unman** [comment]
I had replied to this proposal by email, but gh doesnt show the comment.(?)
I've pasted it here:

That cant be the right solution.

We don't want cacher to *always* return "tor proxy", since it's in the
users hands whether it routes through Tor or not.
In fact returning that is completely unconnected to whether routing is
via Tor. (The case is different in Whonix where that file can be
included and Tor access is supposedly guaranteed.)

I suggest that cacher set:
qubes.UpdatesProxy  *   @tag:whonix-updatevm    @default    allow target=sys-whonix
qubes.UpdatesProxy  *   @tag:whonix-updatevm    @anyvm      deny
qubes.UpdatesProxy  *   @type:TemplateVM        @default    allow target=cacher

IF the current target for @type:TemplateVM is target=sys-whonix, then
the netvm for cacher can be set to sys-whonix. That way Whonix users get
caching for all templates EXCEPT the whonix ones.
This wont capture every case, because users may already be using a
tinyproxy connected to sys-whonix, or using an alternative Tor proxy:
I'm not clear how far we want to dig in to those possibilities.

If the option to update over Tor is enabled, and cacher is already
installed and the default target, then there is no need to adjust the
policy rules. Just set the cacher netvm to sys-whonix.

If we do this then the rewrite option should not be applied in Whonix
templates - is there any grain we can access specific to Whonix?

**Comment by tlaurion** [comment]
> I suggest that cacher set:
> qubes.UpdatesProxy * @tag:whonix-updatevm @default allow target=sys-whonix
> qubes.UpdatesProxy * @tag:whonix-updatevm @anyvm deny
> qubes.UpdatesProxy * @type:TemplateVM @default allow target=cacher

I see that this was implemented under: https://github.com/unman/shaker/commit/0165e7610a904b57821d0126cba6a2952926c7b2#diff-43c52f790288fc13c3c02d23567eb176a98406a79d67faef95cfde777d6539eeR10-R12

> If the option to update over Tor is enabled, and cacher is already
> installed and the default target, then there is no need to adjust the
> policy rules. Just set the cacher netvm to sys-whonix.

> IF the current target for @type:TemplateVM is target=sys-whonix, then
> the netvm for cacher can be set to sys-whonix. That way Whonix users get
> caching for all templates EXCEPT the whonix ones.

Right. But Whonix being based on debian-11 will result in the same debian packages downloaded 3x, even if using cacher: 
- everything debian downloaded packages through cacher (good)
- whonix-gw (meh)
- whonix-ws (meh)

@adrenalos gave a hint into how cacher could instruct whonix to disable tor proxy check when cacher is applied and sys-whonix is enforced to download all updates. 

As said before: 
- if cacher sees at install that sys-whonix is used as update proxy, then cacher could have it's template simply overwrites userinfo.html. whonix templates are already configured to download updates through tor in that case, and if the update proxy doesn't permit tor package download, the update process will fail, where apt will not be able to download packages from tor URLs. 
- Otherwise, @adrelanos gave a hint into [deactivating the tor proxy check](https://github.com/unman/shaker/issues/10#issuecomment-1221372234) under whonix templates (would give the same result as above suggestion: package download failing if update proxy not supporting tor):
> To use the override for testing, torified_check=true could be set in /etc/uwt.d/25_cacher.conf. Untested but I don't see why it wouldn't work.  

@unman @adrelanos: I am not sure how to properly have both coexist, while I still see a big advantage for everyone waiting for https://github.com/QubesOS/qubes-issues/issues/1957

**Comment by tlaurion** [comment]
Ideal solution would be Whonix templates actually testing for tor addresses reachability instead of relaying on crafted tinyproxy proxy response/apt-cacher response.

This is detailed https://github.com/unman/shaker/issues/10#issuecomment-1230741971

I agree with @unman, it should not be cacher's responsibility to hack into Whonix templates for them to bypass their checks or fake its own to comply with expected hardcoded tinyproxy responses hacked into returned tinyproxy webpage per Whonix-gw modification.

Closing. This discussion should continue under #10
